import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/app/provider/Theme-provider";
import { Bungee, Josefin_Sans } from "next/font/google";
import CreateQuizModal from "@/components/modal/CreateQuizModal";
export const metadata: Metadata = {
  title: "Quizify Quiz App",
  description: "Generated by create next app",
};

export const bungee = Bungee({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bungee",
});

export const josefin = Josefin_Sans({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-josefin",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bungee.variable} ${josefin.variable} anitalised min-h-screen relative`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Navbar />
          <CreateQuizModal />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
